version: '3.8'

services:

  postgres:
    image: postgres:14
    container_name: incident-db
    environment:
      POSTGRES_DB: incident_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: nksuHj786687
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: /Users/admin/Downloads/incident-intelligence
      dockerfile: Dockerfile
    container_name: incident-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/incident_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: nksuHj786687

volumes:
  postgres_data: